### PR TITLE
Added support ES6 support

### PR DESCRIPTION
**Pull request by chriz-hoepfner**
Hi, ich hab für Coureon im Starter ES6 Support ergänzt. Kann das mit rein?

Beste Grüße,
Chris

### CODE REVIEW

**Comment by jonathan-reisdorf** [comment]
sounds good. :+1:  let me check if that would significantly slow down build process for developers not using ES6..

**Comment by jonathan-reisdorf** [comment]
Even with the empty javascript file, build process is about 700ms slower when using babelify. That doesn't mean we shouldn't merge it in.
But maybe it gets more important now to enable incremental building as well:
https://github.com/babel/babelify/issues/116

I'm open for any PRs on this :)

**Comment by stryju** [comment]
if i may:

i'd keep any browserify plugin / transformation away from the main task as you can easily add the plugins / transformations in `package.json` under `browserify` field - this way the task stays clean and your project can take advantage of transformations it needs
more on that [here](https://github.com/substack/browserify-handbook#browserifytransform-field)

example:

```js
{
  "devDependencies": {
    "babelify": "^6.3.0",
    "browserify": "^11.1.0"
  },
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "ignore": [
            "/angular/"
          ]
        }
      ]
    ]
  }
}
```

**Comment by jonathan-reisdorf** [comment]
@stryju sounds good, I currently don't have any time on my hands, but will do the change later

**Pull request merged**
